# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Socializa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Socializa

  target 'SocializaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
end
